#ifndef FREERTOS_CHIP_SPECIFIC_EXTENSIONS_H
#define FREERTOS_CHIP_SPECIFIC_EXTENSIONS_H

#define portasmHAS_CLINT 1
#define portasmADDITIONAL_CONTEXT_SIZE 0

.macro portasmSAVE_ADDITIONAL_REGISTERS
    .endm
    
.macro portasmRESTORE_ADDITIONAL_REGISTERS
    .endm

#endif /*FREERTOS_CHIP_SPECIFIC_EXTENSIONS_H*/